package com.chat.common.entity;

public class Player {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.id
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.name
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.password
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.level
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.exp
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    private Integer exp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.id
     *
     * @return the value of player.id
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.id
     *
     * @param id the value for player.id
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.name
     *
     * @return the value of player.name
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.name
     *
     * @param name the value for player.name
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.password
     *
     * @return the value of player.password
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.password
     *
     * @param password the value for player.password
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.level
     *
     * @return the value of player.level
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.level
     *
     * @param level the value for player.level
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.exp
     *
     * @return the value of player.exp
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.exp
     *
     * @param exp the value for player.exp
     *
     * @mbggenerated Tue Oct 23 17:55:52 CST 2018
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }
}